### ISSUE TITLE
Server crash due to response from one client

### ISSUE THREAD

**Issue by AyushyaChitransh** [goerli/ethstats-server#17]
The error log is as follows:

```
/root/ethstats-server/lib/history.js:339
                .value();
                 ^

TypeError: _(...).sortBy(...).slice(...).forEach(...).reverse(...).value is not a function
    at History.getNodePropagation (/root/ethstats-server/lib/history.js:339:4)
    at Collection.addBlock (/root/ethstats-server/lib/collection.js:88:46)
    at Sparky.<anonymous> (/root/ethstats-server/app.js:185:10)
    at emitOne (events.js:116:13)
    at Sparky.emit (events.js:211:7)
    at Sparky.incoming (/root/ethstats-server/node_modules/primus-emit/index.js:72:44)
    at transform (/root/ethstats-server/node_modules/primus/spark.js:312:33)
    at Sparky.transforms (/root/ethstats-server/node_modules/primus/spark.js:330:4)
    at decoding (/root/ethstats-server/node_modules/primus/spark.js:215:13)
    at Sparky.decoder (/root/ethstats-server/node_modules/primus/parsers/json.js:34:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ethstats-server@0.2.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ethstats-server@0.2.0 start script.
```

Another instance of failure resulted in different logs. This failure was caused when netstats server was restarted and client reconnected itself:

```
2019-03-12 07:45:31.368 [API] [CON] Connected auth03Localhost
/root/ethstats-server/lib/history.js:286
        if( !_.isUndefined(best.height) )
                                ^

TypeError: Cannot read property 'height' of undefined
    at History.bestBlockNumber (/root/ethstats-server/lib/history.js:286:26)
    at Collection.canNodeUpdate (/root/ethstats-server/lib/collection.js:305:55)
    at Collection.requiresUpdate (/root/ethstats-server/lib/collection.js:315:16)
    at Sparky.<anonymous> (/root/ethstats-server/app.js:335:14)
    at emitOne (events.js:116:13)
    at Sparky.emit (events.js:211:7)
    at Sparky.incoming (/root/ethstats-server/node_modules/primus-emit/index.js:72:44)
    at transform (/root/ethstats-server/node_modules/primus/spark.js:312:33)
    at Sparky.transforms (/root/ethstats-server/node_modules/primus/spark.js:330:4)
    at decoding (/root/ethstats-server/node_modules/primus/spark.js:215:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ethstats-server@0.2.0 start: `node ./bin/www`
```

Related to #10

**Comment by OleksandrMykytenko** [comment]
The same error for me:
`TypeError: Cannot read property 'height' of undefined`

Any updates here?

**Comment by Zergity** [comment]
Reverting commit 6ad9c2cd5e1112c7f64c4d17f3bf6d180e9497c0 makes it works.
One more thing, this issue happens to only 1 of my 2 Linux systems.

**Comment by PatrickDehkordi** [comment]
Same

**Comment by antsankov** [comment]
Can confirm this issue is still ongoing - unable to use this application at the moment.

**Comment by PatrickDehkordi** [comment]
Hi all I got this wokring a while back. I am on a plane, and on vacation, but will send fix later. Also part of it is I didn't even document all the things I tried and changed. 

However I have a node up now that I SHOULD NOT crash https://goerli.network try adding node, if you want to confrim. Cause alone I can only test so many nodes. 
hope this helps, and thanks everyone for contributing code to this.

**Comment by PatrickDehkordi** [comment]
Also I was able to bring up stable nodes on all the networks:
https://goethereum.network
https://ropsten.net
https://rinkeby.network
https://goerli.network

I think the monitoring that Cudebro wrote is very useful when doing dev on the testnets. I alwasy run it in the background. Feel free to utilize.

**Comment by sebaponti** [comment]
> Reverting commit [6ad9c2c](https://github.com/goerli/ethstats-server/commit/6ad9c2cd5e1112c7f64c4d17f3bf6d180e9497c0) makes it works.
> One more thing, this issue happens to only 1 of my 2 Linux systems.

This solution doesn't work for me, I'm still having the same error

`TypeError: Cannot read property 'height' of undefined`
